export type Database = {
    public: {
      Tables: {
        user_profiles: {
          Row: {
            id: string;
            clerk_id: string;
            first_name: string;
            last_name: string;
            email: string;
            school: string | null;
            grade: string | null;
            bio: string | null;
            phone_number: string | null;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            clerk_id: string;
            first_name: string;
            last_name: string;
            email: string;
            school?: string | null;
            grade?: string | null;
            bio?: string | null;
            phone_number?: string | null;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            clerk_id?: string;
            first_name?: string;
            last_name?: string;
            email?: string;
            school?: string | null;
            grade?: string | null;
            bio?: string | null;
            phone_number?: string | null;
            created_at?: string;
            updated_at?: string;
          };
        };
        discount_codes: {
          Row: {
            id: string;
            code: string;
            discount_amount: number;
            discount_type: string;
            valid_until: string;
            applicable_courses: string[] | null;
            created_at: string | null;
            is_used: boolean | null;
            used_by: string | null;
            used_at: string | null;
            influencer_id: string | null;
            campaign_id: string | null;
            commission: number | null;
            is_referral: boolean;
            max_usage: number;
            usage_count: number;
            is_campaign: boolean;
            campaign_name: string | null;
            campaign_description: string | null;
            campaign_cover_image: string | null;
            has_balance_limit: boolean;
            remaining_balance: number | null;
            owner_id: string | null;
            initial_balance: number | null;
          };
          Insert: {
            id?: string;
            code: string;
            discount_amount: number;
            discount_type: string;
            valid_until: string;
            applicable_courses?: string[] | null;
            created_at?: string | null;
            is_used?: boolean | null;
            used_by?: string | null;
            used_at?: string | null;
            influencer_id?: string | null;
            campaign_id?: string | null;
            commission?: number | null;
            is_referral?: boolean;
            max_usage?: number;
            usage_count?: number;
            is_campaign?: boolean;
            campaign_name?: string | null;
            campaign_description?: string | null;
            campaign_cover_image?: string | null;
            has_balance_limit?: boolean;
            remaining_balance?: number | null;
            owner_id?: string | null;
            initial_balance?: number | null;
          };
          Update: {
            id?: string;
            code?: string;
            discount_amount?: number;
            discount_type?: string;
            valid_until?: string;
            applicable_courses?: string[] | null;
            created_at?: string | null;
            is_used?: boolean | null;
            used_by?: string | null;
            used_at?: string | null;
            influencer_id?: string | null;
            campaign_id?: string | null;
            commission?: number | null;
            is_referral?: boolean;
            max_usage?: number;
            usage_count?: number;
            is_campaign?: boolean;
            campaign_name?: string | null;
            campaign_description?: string | null;
            campaign_cover_image?: string | null;
            has_balance_limit?: boolean;
            remaining_balance?: number | null;
            owner_id?: string | null;
            initial_balance?: number | null;
          };
        };
        hero_slides: {
          Row: {
            id: number;
            locale: string;
            title: string;
            subtitle: string | null;
            description: string;
            button_text: string;
            button_link: string;
            secondary_button_text: string | null;
            secondary_button_link: string | null;
            image_url: string;
            is_active: boolean;
            sort_order: number;
            created_at: string;
            updated_at: string;
          };
        };
        myuni_events: {
          Row: {
            id: string;
            slug: string;
            title: string;
            description: string | null;
            organizer_name: string | null;
            organizer_email: string | null;
            organizer_linkedin: string | null;
            organizer_image_url: string | null;
            event_type: 'workshop' | 'seminar' | 'conference' | 'meetup' | 'webinar';
            category: string | null;
            tags: string[] | null;
            start_date: string;
            end_date: string | null;
            timezone: string;
            duration_minutes: number | null;
            is_online: boolean;
            location_name: string | null;
            location_address: string | null;
            meeting_url: string | null;
            is_paid: boolean;
            price: number | null;
            max_attendees: number | null;
            current_attendees: number;
            registration_deadline: string | null;
            is_registration_open: boolean;
            thumbnail_url: string | null;
            banner_url: string | null;
            status: 'upcoming' | 'ongoing' | 'completed' | 'cancelled';
            is_active: boolean;
            is_featured: boolean;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            slug: string;
            title: string;
            description?: string | null;
            organizer_name?: string | null;
            organizer_email?: string | null;
            organizer_linkedin?: string | null;
            organizer_image_url?: string | null;
            event_type?: 'workshop' | 'seminar' | 'conference' | 'meetup' | 'webinar';
            category?: string | null;
            tags?: string[] | null;
            start_date: string;
            end_date?: string | null;
            timezone?: string;
            duration_minutes?: number | null;
            is_online?: boolean;
            location_name?: string | null;
            location_address?: string | null;
            meeting_url?: string | null;
            is_paid?: boolean;
            price?: number | null;
            max_attendees?: number | null;
            current_attendees?: number;
            registration_deadline?: string | null;
            is_registration_open?: boolean;
            thumbnail_url?: string | null;
            banner_url?: string | null;
            status?: 'upcoming' | 'ongoing' | 'completed' | 'cancelled';
            is_active?: boolean;
            is_featured?: boolean;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            slug?: string;
            title?: string;
            description?: string | null;
            organizer_name?: string | null;
            organizer_email?: string | null;
            organizer_linkedin?: string | null;
            organizer_image_url?: string | null;
            event_type?: 'workshop' | 'seminar' | 'conference' | 'meetup' | 'webinar';
            category?: string | null;
            tags?: string[] | null;
            start_date?: string;
            end_date?: string | null;
            timezone?: string;
            duration_minutes?: number | null;
            is_online?: boolean;
            location_name?: string | null;
            location_address?: string | null;
            meeting_url?: string | null;
            is_paid?: boolean;
            price?: number | null;
            max_attendees?: number | null;
            current_attendees?: number;
            registration_deadline?: string | null;
            is_registration_open?: boolean;
            thumbnail_url?: string | null;
            banner_url?: string | null;
            status?: 'upcoming' | 'ongoing' | 'completed' | 'cancelled';
            is_active?: boolean;
            is_featured?: boolean;
            created_at?: string;
            updated_at?: string;
          };
        };
        myuni_case_result: {
          Row: {
            id: string;
            participant_name: string;
            contact_email: string;
            backup_email: string | null;
            subject: string | null;
            highlight_direction: string | null;
            general_score: number | null;
            comments: string | null;
            second_instructor_score: number | null;
            average_score: number | null;
            second_comments: string | null;
            user_id: string | null;
            created_at: string;
            updated_at: string;
          };
          Insert: {
            id?: string;
            participant_name: string;
            contact_email: string;
            backup_email?: string | null;
            subject?: string | null;
            highlight_direction?: string | null;
            general_score?: number | null;
            comments?: string | null;
            second_instructor_score?: number | null;
            average_score?: number | null;
            second_comments?: string | null;
            user_id?: string | null;
            created_at?: string;
            updated_at?: string;
          };
          Update: {
            id?: string;
            participant_name?: string;
            contact_email?: string;
            backup_email?: string | null;
            subject?: string | null;
            highlight_direction?: string | null;
            general_score?: number | null;
            comments?: string | null;
            second_instructor_score?: number | null;
            average_score?: number | null;
            second_comments?: string | null;
            user_id?: string | null;
            created_at?: string;
            updated_at?: string;
          };
        };
      };
    };
  };